# Generated by Django 4.1.7 on 2023-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_cart_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка'),
        ),
    ]
